# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec28f2b505e0b721041da035ad8edfda1276bc28dac1c86dd028089287bc9ec8b4b58ccd38e20f1cffa56baeadff0a56ca4f4d6fa28d698f28fb89b97dd56d01

test:
  secret_key_base: e10e7e252c74ecbf6addd5771dfeea02dfc791a9fa7c139339fc66fbfbafd7c968030ed7f1be84ebd31dc88aecf40e2ea9e09af68ed8e5d3d24e3a8c028579ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
